// eventReport/index.js
// Runs every hour.
// Finds events that ended in the last hour.
// Generates a PDF attendance report and emails it to the organiser.
// Then marks the event as COMPLETED.

const { PrismaClient } = require('@prisma/client');
const nodemailer = require('nodemailer');
const PDFDocument = require('pdfkit');

const prisma = new PrismaClient();

module.exports = async function (context, myTimer) {
  context.log('⏰ Event report function triggered');

  const now = new Date();
  const oneHourAgo = new Date(now.getTime() - 60 * 60 * 1000);

  try {
    // Find PUBLISHED events whose date passed in the last hour
    const endedEvents = await prisma.event.findMany({
      where: {
        status: 'PUBLISHED',
        eventDate: {
          gte: oneHourAgo,
          lte: now,
        },
      },
      include: {
        organizer: { select: { name: true, email: true } },
        bookings: {
          where: { status: 'CONFIRMED' },
          include: { tickets: true },
        },
        attendance: {
          where: { status: 'PRESENT' },
        },
      },
    });

    context.log(`Found ${endedEvents.length} events that just ended`);

    for (const event of endedEvents) {
      // Calculate stats
      const totalTicketsSold = event.bookings.reduce(
        (sum, b) => sum + b.tickets.length, 0
      );
      const totalAttended = event.attendance.length;
      const noShows = totalTicketsSold - totalAttended;
      const attendanceRate =
        totalTicketsSold > 0
          ? Math.round((totalAttended / totalTicketsSold) * 100)
          : 0;
      const totalRevenue = event.bookings.reduce(
        (sum, b) => sum + parseFloat(b.totalAmount || 0), 0
      );

      const stats = { totalTicketsSold, totalAttended, noShows, attendanceRate, totalRevenue };

      // Generate PDF
      const pdfBuffer = await generatePDF(event, stats);

      // Email PDF to organiser
      await sendEmail({
        to: event.organizer.email,
        name: event.organizer.name,
        eventTitle: event.title,
        eventDate: event.eventDate,
        pdfBuffer,
        stats,
      });

      // Mark event as COMPLETED
      await prisma.event.update({
        where: { id: event.id },
        data: { status: 'COMPLETED' },
      });

      context.log(`✅ Report sent for: "${event.title}" → ${event.organizer.email}`);
    }
  } catch (err) {
    context.log.error('Event report function error:', err);
  } finally {
    await prisma.$disconnect();
  }
};

// ─── PDF Generator ────────────────────────────────────────────────────
function generatePDF(event, stats) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50 });
    const chunks = [];
    doc.on('data', c => chunks.push(c));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    // Title
    doc.fontSize(22).fillColor('#6366f1').text('Event Attendance Report', { align: 'center' });
    doc.moveDown(0.4);
    doc.fontSize(17).fillColor('#111827').text(event.title, { align: 'center' });
    doc.fontSize(11).fillColor('#6b7280').text(
      new Date(event.eventDate).toLocaleDateString('en-US', {
        weekday: 'long', year: 'numeric', month: 'long', day: 'numeric',
        hour: '2-digit', minute: '2-digit',
      }),
      { align: 'center' }
    );
    doc.moveDown(0.3);
    doc.fontSize(11).fillColor('#6b7280').text(`Venue: ${event.venue}`, { align: 'center' });

    // Divider
    doc.moveDown(1);
    doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor('#e5e7eb').stroke();
    doc.moveDown(1);

    // Stats table
    doc.fontSize(14).fillColor('#111827').text('Summary', { underline: true });
    doc.moveDown(0.5);

    const rows = [
      ['Tickets Sold', stats.totalTicketsSold],
      ['Attendees Scanned In', stats.totalAttended],
      ['No-Shows', stats.noShows],
      ['Attendance Rate', `${stats.attendanceRate}%`],
      ['Total Revenue Collected', `PKR ${stats.totalRevenue.toLocaleString()}`],
    ];

    rows.forEach(([label, value], i) => {
      const y = doc.y;
      if (i % 2 === 0) {
        doc.rect(50, y - 4, 495, 20).fillColor('#f9fafb').fill();
      }
      doc.fillColor('#374151').fontSize(11).text(label, 60, y, { continued: true, width: 250 });
      doc.fillColor('#6366f1').text(String(value), { align: 'right' });
      doc.moveDown(0.2);
    });

    // Footer
    doc.moveDown(2);
    doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor('#e5e7eb').stroke();
    doc.moveDown(0.5);
    doc.fontSize(9).fillColor('#9ca3af').text(
      `Auto-generated by Event Management System on ${new Date().toLocaleString()}`,
      { align: 'center' }
    );

    doc.end();
  });
}

// ─── Email Sender ──────────────────────────────────────────────────────
async function sendEmail({ to, name, eventTitle, pdfBuffer, stats }) {
  const transporter = nodemailer.createTransport({
    host: process.env.SMTP_HOST || 'smtp.gmail.com',
    port: parseInt(process.env.SMTP_PORT || '587'),
    secure: false,
    auth: { user: process.env.SMTP_USER, pass: process.env.SMTP_PASS },
  });

  const filename = `${eventTitle.replace(/[^a-z0-9]/gi, '_')}_report.pdf`;

  await transporter.sendMail({
    from: process.env.EMAIL_FROM,
    to,
    subject: `📊 Attendance Report Ready — ${eventTitle}`,
    html: `
      <div style="font-family:Arial,sans-serif;max-width:580px;margin:auto;color:#111827">
        <h2 style="color:#6366f1">Your Event Report is Ready</h2>
        <p>Hi ${name},</p>
        <p>Your event <strong>${eventTitle}</strong> has ended. Here's the summary:</p>
        <table style="width:100%;border-collapse:collapse;margin:20px 0;font-size:14px">
          <tr style="background:#f3f4f6"><td style="padding:10px 14px;font-weight:600">Tickets Sold</td><td style="padding:10px 14px">${stats.totalTicketsSold}</td></tr>
          <tr><td style="padding:10px 14px;font-weight:600">Attended</td><td style="padding:10px 14px">${stats.totalAttended}</td></tr>
          <tr style="background:#f3f4f6"><td style="padding:10px 14px;font-weight:600">No-Shows</td><td style="padding:10px 14px">${stats.noShows}</td></tr>
          <tr><td style="padding:10px 14px;font-weight:600">Attendance Rate</td><td style="padding:10px 14px;color:#6366f1;font-weight:700">${stats.attendanceRate}%</td></tr>
          <tr style="background:#f3f4f6"><td style="padding:10px 14px;font-weight:600">Revenue</td><td style="padding:10px 14px">PKR ${stats.totalRevenue.toLocaleString()}</td></tr>
        </table>
        <p>The full PDF report is attached to this email.</p>
        <p style="color:#9ca3af;font-size:11px;margin-top:24px">Sent automatically by Event Management System</p>
      </div>
    `,
    attachments: [{ filename, content: pdfBuffer, contentType: 'application/pdf' }],
  });
}