name: Deploy Frontend to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install frontend dependencies
        working-directory: ./event-frontend
        run: npm install

      - name: Build frontend
        working-directory: ./event-frontend
        run: npm run build
        env:
          REACT_APP_API_URL: https://event-backend-iba-fzbkbpdqb6f9f2am.uaenorth-01.azurewebsites.net
          CI: false

      - name: Prepare deployment folder
        run: |
          mkdir -p deploy-output
          cp -r event-frontend/build/* deploy-output/
          cp event-frontend/server.js deploy-output/server.js
          echo '{"name":"frontend","version":"1.0.0","scripts":{"start":"node server.js"},"dependencies":{"express":"^4.19.2"}}' > deploy-output/package.json
          cd deploy-output && npm install --omit=dev

      - name: Zip deployment folder contents
        working-directory: ./deploy-output
        run: zip -r ../frontend-deploy.zip .

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'event-frontend-iba'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_FRONTEND }}
          package: ./frontend-deploy.zip